<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Discussion – Green Space Configuration and Pluvial Flood Risk</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../sections/conclusion.html" rel="next">
<link href="../sections/typology.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ffc4c3fc79587ee79da4865b6a08975e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../sections/discussion.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discussion</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Green Space Configuration and Pluvial Flood Risk</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/problem_statement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Problem statement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/preliminary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Preliminary maps and research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metric selection and redundancy check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/typology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Typology construction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/discussion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sections/appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Additional outputs and unused material</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#results-and-analysis" id="toc-results-and-analysis" class="nav-link active" data-scroll-target="#results-and-analysis"><span class="header-section-number">6.1</span> Results and analysis</a></li>
  <li><a href="#interpretation-of-delft-and-xian-typologies" id="toc-interpretation-of-delft-and-xian-typologies" class="nav-link" data-scroll-target="#interpretation-of-delft-and-xian-typologies"><span class="header-section-number">6.2</span> Interpretation of Delft and Xi’an typologies</a></li>
  <li><a href="#nature-based-solution-directions" id="toc-nature-based-solution-directions" class="nav-link" data-scroll-target="#nature-based-solution-directions"><span class="header-section-number">6.3</span> Nature based solution directions</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.4</span> Limitations</a></li>
  <li><a href="#reproducibility-statement-and-ai-use" id="toc-reproducibility-statement-and-ai-use" class="nav-link" data-scroll-target="#reproducibility-statement-and-ai-use"><span class="header-section-number">6.5</span> Reproducibility statement and AI use</a></li>
  <li><a href="#future-improvements" id="toc-future-improvements" class="nav-link" data-scroll-target="#future-improvements"><span class="header-section-number">6.6</span> Future improvements</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/edit/main/sections/discussion.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/blob/main/sections/discussion.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Discussion</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This chapter brings together the main analytical results, their interpretation, the limitations of the workflow, and the reproducibility of the project. The separate results are not discussed as isolated outputs here, but are linked back to the research question: how green space configuration relates to pluvial flood related surface water patterns in Delft and Xi’an.</p>
<section id="results-and-analysis" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="results-and-analysis"><span class="header-section-number">6.1</span> Results and analysis</h2>
<p>The correlation analysis compared green space configuration metrics with FWEI derived flood indicators. The main aim was to check whether greener, more compact, or more isolated green space patterns were associated with higher or lower detected surface water values.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>City</th>
<th>Green-space metric</th>
<th style="text-align: right;">FWEI change mean</th>
<th style="text-align: right;">Flood share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Delft</td>
<td>Green percentage</td>
<td style="text-align: right;">0.242</td>
<td style="text-align: right;">0.344</td>
</tr>
<tr class="even">
<td>Delft</td>
<td>Contiguity</td>
<td style="text-align: right;">0.196</td>
<td style="text-align: right;">0.344</td>
</tr>
<tr class="odd">
<td>Delft</td>
<td>Nearest-neighbour distance</td>
<td style="text-align: right;">-0.087</td>
<td style="text-align: right;">-0.083</td>
</tr>
<tr class="even">
<td>Xi’an</td>
<td>Green percentage</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.367</td>
</tr>
<tr class="odd">
<td>Xi’an</td>
<td>Contiguity</td>
<td style="text-align: right;">0.073</td>
<td style="text-align: right;">0.216</td>
</tr>
<tr class="even">
<td>Xi’an</td>
<td>Nearest-neighbour distance</td>
<td style="text-align: right;">-0.039</td>
<td style="text-align: right;">-0.054</td>
</tr>
</tbody>
</table>
<p>The strongest relationships are found with <code>flood_share</code>, not with <code>fwei_change_mean</code>. In both cities, green percentage and contiguity have positive correlations with flood share. This means that cells with more green space or more connected green patches also tend to have a larger share of detected surface water increase. The nearest neighbour distance metric has weak negative correlations, meaning that more isolated green patches are not linked to higher detected water values in the same way.</p>
<div id="fig-correlation-overview" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/results/correlation_overview.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;6.1: Correlation between green-space metrics and FWEI-derived flood-pattern indicators."><img src="../figures/results/correlation_overview.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Correlation between green-space metrics and FWEI-derived flood-pattern indicators.
</figcaption>
</figure>
</div>
<p>The correlation results do not support the simple assumption that more green space automatically means less detected water. Instead, the results show that green space configuration and FWEI derived surface water increase overlap spatially in some parts of both cities.</p>
<p>The final combined typology gives a clearer interpretation than the correlations alone. It combines green space configuration, FWEI derived flood pattern indicators, and DEM variables into one shared classification.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Main results of the final shared green+flood+DEM typology.</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">City</th>
<th style="text-align: left;">Type</th>
<th style="text-align: right;">Cells</th>
<th style="text-align: right;">Share</th>
<th style="text-align: right;">Green</th>
<th style="text-align: right;">Contiguity</th>
<th style="text-align: right;">FWEI_change</th>
<th style="text-align: right;">Flood_share</th>
<th style="text-align: right;">Flood_patches</th>
<th style="text-align: right;">Elevation</th>
<th style="text-align: right;">Slope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 1</td>
<td style="text-align: right;">2088</td>
<td style="text-align: right;">20.9</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">0.235</td>
<td style="text-align: right;">-0.056</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-2.58</td>
<td style="text-align: right;">0.204</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 2</td>
<td style="text-align: right;">5753</td>
<td style="text-align: right;">57.5</td>
<td style="text-align: right;">19.2</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">2.53</td>
<td style="text-align: right;">-1.87</td>
<td style="text-align: right;">0.256</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 3</td>
<td style="text-align: right;">2061</td>
<td style="text-align: right;">20.6</td>
<td style="text-align: right;">49.5</td>
<td style="text-align: right;">0.567</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">0.640</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">-2.11</td>
<td style="text-align: right;">0.475</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 4</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">49.7</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.168</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">-0.81</td>
<td style="text-align: right;">1.055</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 1</td>
<td style="text-align: right;">1432</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">0.590</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">393.44</td>
<td style="text-align: right;">0.466</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 2</td>
<td style="text-align: right;">407</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">398.34</td>
<td style="text-align: right;">0.328</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 3</td>
<td style="text-align: right;">861</td>
<td style="text-align: right;">8.6</td>
<td style="text-align: right;">65.1</td>
<td style="text-align: right;">0.769</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">0.610</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">398.76</td>
<td style="text-align: right;">0.808</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 4</td>
<td style="text-align: right;">7300</td>
<td style="text-align: right;">73.0</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">0.568</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.144</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">400.00</td>
<td style="text-align: right;">0.565</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The main result is that Delft and Xi’an have different dominant typology structures, but the shared Type 3 class contains the strongest FWEI derived surface water values in both cities.</p>
</section>
<section id="interpretation-of-delft-and-xian-typologies" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interpretation-of-delft-and-xian-typologies"><span class="header-section-number">6.2</span> Interpretation of Delft and Xi’an typologies</h2>
<p>In Delft, Type 2 is the dominant combined typology. It covers about 58% of the study area and represents the main background condition. It has lower green coverage and lower detected surface water values than Type 3. Type 3 covers about 21% of the study area, but it has the highest flood share, 0.640, and the highest mean FWEI change, 0.075. This means that the strongest detected surface water pattern in Delft is concentrated in a greener and more connected type, not in the lowest green type.</p>
<div id="fig-results-delft-final-typology" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-results-delft-final-typology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/results/combined_typologies/delft_green_flood_dem_type_context_overview.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;6.2: Final green+flood+DEM typology in Delft."><img src="../figures/results/combined_typologies/delft_green_flood_dem_type_context_overview.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-results-delft-final-typology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Final green+flood+DEM typology in Delft.
</figcaption>
</figure>
</div>
<p>Type 1 also covers about 21% of Delft, but it has almost no detected surface water increase. Type 4 has high green coverage and relatively many detected flood patches, but it covers less than 1% of the study area. It is therefore too small to treat as a major Delft wide pattern.</p>
<p>In Xi’an, Type 4 is the dominant combined typology. It covers about 73% of the study area and represents the main background condition. It has moderate green coverage and moderate flood share, but it also has the highest mean number of detected flood patches. This means that much of Xi’an is classified as a widespread type with fragmented detected surface water patterns.</p>
<div id="fig-results-xian-final-typology" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-results-xian-final-typology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/results/combined_typologies/xian_green_flood_dem_type_context_overview.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;6.3: Final green+flood+DEM typology in Xi’an."><img src="../figures/results/combined_typologies/xian_green_flood_dem_type_context_overview.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-results-xian-final-typology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Final green+flood+DEM typology in Xi’an.
</figcaption>
</figure>
</div>
<p>The clearest high water type in Xi’an is Type 3. It covers only about 9% of the study area, but it has the highest green percentage, highest contiguity, highest FWEI change, and highest flood share. Its mean flood share is 0.610 and its mean FWEI change is 0.065. This makes Type 3 the strongest combined green+flood+DEM type in Xi’an, even though it is not the largest type.</p>
<p>A specific issue in Xi’an is the narrow Type 1 band along the northern edge of the typology map. This band is a grid alignment artefact from preprocessing. It is not interpreted as a real typology zone. This also means that the reported Type 1 percentage in Xi’an is overestimated. The corrected share was not recalculated, so the table values are kept as produced by the workflow, but the interpretation does not rely on this edge band.</p>
<p>Overall, Delft has a more mixed typology structure, while Xi’an is more strongly dominated by one background type. However, both cities show that the strongest detected surface water values occur in the greener and more contiguous Type 3 class.</p>
</section>
<section id="nature-based-solution-directions" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="nature-based-solution-directions"><span class="header-section-number">6.3</span> Nature based solution directions</h2>
<p>The final typology was also used to identify which types are most relevant for nature based solution discussion. This is not a measured flood risk ranking. It is only a practical interpretation based on the available green space, FWEI derived flood, and DEM indicators.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Typology candidates for planning interpretation.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 50%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">City</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Interpretation</th>
<th style="text-align: left;">Solution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 3</td>
<td style="text-align: left;">green area with detected water, possibly storage or easier detection</td>
<td style="text-align: left;">floodable parks, retention basins, wetland enhancement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 2</td>
<td style="text-align: left;">low green and relatively high detected water</td>
<td style="text-align: left;">depaving, rain gardens, permeable surfaces</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 4</td>
<td style="text-align: left;">green area with detected water, possibly storage or easier detection</td>
<td style="text-align: left;">floodable parks, retention basins, wetland enhancement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delft</td>
<td style="text-align: left;">Type 1</td>
<td style="text-align: left;">less problematic or unclear</td>
<td style="text-align: left;">no clear solution from typology alone</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 3</td>
<td style="text-align: left;">green area with detected water, possibly storage or easier detection</td>
<td style="text-align: left;">floodable parks, retention basins, wetland enhancement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 4</td>
<td style="text-align: left;">many separate detected water patches</td>
<td style="text-align: left;">bioswales, green corridors, connected pocket parks</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 2</td>
<td style="text-align: left;">less problematic or unclear</td>
<td style="text-align: left;">no clear solution from typology alone</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xi’an</td>
<td style="text-align: left;">Type 1</td>
<td style="text-align: left;">less problematic or unclear</td>
<td style="text-align: left;">no clear solution from typology alone</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For Delft, Type 3 is the main candidate. Since this type already has relatively high green coverage, the planning question is not simply where to add more green space. A more relevant direction is to improve the water storage function of existing green areas. Possible interventions include floodable parks, retention basins, wetland enhancement, and controlled temporary storage areas.</p>
<p>Type 2 in Delft is also relevant because it is the dominant background type. However, its flood values are much lower than Type 3, so it is less urgent as a high water typology. If interventions were considered there, they would more likely focus on small scale improvements such as depaving, rain gardens, and permeable surfaces.</p>
<p>For Xi’an, Type 3 is again the clearest high water green type. Type 4 is also important because it covers most of the study area and has many separate detected flood patches. This suggests a more fragmented surface water pattern across the urban area. Possible interventions could include bioswales, connected pocket parks, green corridors, rain gardens, and local infiltration measures.</p>
<p>These suggestions should be treated as planning directions, not final design proposals. The analysis uses FWEI derived surface water change, not measured flood depth. Therefore, the typology can identify relevant spatial patterns, but it cannot determine exact engineering solutions.</p>
</section>
<section id="limitations" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.4</span> Limitations</h2>
<p>The main limitation is that FWEI is a proxy for flood related surface water change. It does not measure flood depth, water volume, drainage failure, or flood damage. The <code>flood_share</code> variable is also based on a threshold applied to FWEI change, so it should be interpreted as detected surface water increase rather than a confirmed flood depth map.</p>
<p>This limitation became clear during the data search. For Delft, a local dataset for water depth during intense rainfall was available. This type of dataset would have been more directly useful for analysing pluvial flooding, because it represents water depth instead of relying on a satellite derived proxy.</p>
<div id="fig-delft-water-depth-discussion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-delft-water-depth-discussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/discussion/delft_water_depth_intense_rainfall.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;6.4: Example of Delft water depth during intense rainfall."><img src="../figures/discussion/delft_water_depth_intense_rainfall.png" class="img-fluid figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-delft-water-depth-discussion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Example of Delft water depth during intense rainfall.
</figcaption>
</figure>
</div>
<p>A comparable water depth dataset for Xi’an was not available during the project. We also tried to contact researchers who had used similar pluvial flood or water depth data for Xi’an, in the hope that the dataset could be accessed. However, we did not receive a response. Because the Delft water depth layer could not be matched with an equivalent Xi’an layer, it was not used in the main comparative analysis.</p>
<p>If comparable water depth maps had been available for both cities, the analysis would have been stronger. The relationship between green space configuration and pluvial flooding could then have been tested more directly, without relying mainly on FWEI as a proxy. It would also have been possible to validate whether the FWEI derived surface water patterns matched actual flood depth patterns.</p>
<p>A second limitation is that the analysis does not include all factors that influence pluvial flooding. Surface water accumulation is also affected by other variables such as sewer capacity, drainage systems, soil type, surface materials, etc. Because these variables were not equally available for Delft and Xi’an, they could not be included in the shared typology, which means that some local causes of surface water accumulation is missing from the interpretation.</p>
<p>A third limitation is the 100 m by 100 m grid. The grid makes comparison easier, but it also simplifies the urban landscape. Small local features such as narrow streets, small green strips, local depressions, or drainage channels can be averaged inside one grid cell. A different grid size could therefore produce somewhat different results.</p>
<p>A fourth limitation is the K-means clustering method. The final typology depends on the selected input variables and the chosen number of clusters. Four clusters were selected because they were interpretable and manageable, but another number of clusters could produce a different typology structure.</p>
</section>
<section id="reproducibility-statement-and-ai-use" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="reproducibility-statement-and-ai-use"><span class="header-section-number">6.5</span> Reproducibility statement and AI use</h2>
<p>The workflow is partly reproducible. After the input data are prepared, the R scripts can be used to produce the grid cell metrics, metric selection outputs, correlation tables, maps, and final typologies. The main scripts and report files are included in the GitHub repository, while the necessary larger datasets are stored in the shared SURFdrive folder.</p>
<p>The repository is organised so that the report can be rendered with Quarto. The main outputs are stored in <code>data/results</code> and <code>figures/results</code>. The most important R scripts are used for calculating green space metrics, generating maps and plots, selecting metrics, and producing the final combined typologies. A README file describes the repository structure, the main scripts, the data folders, and the steps needed to rerun or render the analysis.</p>
<p>The workflow is not fully automatic from the very beginning. Some preprocessing steps are necessary, including finding suitable datasets, clipping the study areas, checking coordinate reference systems, preparing input layers, and deciding which datasets were comparable between Delft and Xi’an. These manual decisions are important because they influence the final outputs.</p>
<p>AI tools were used during the project as support for writing, structuring the report, checking R code and combining scripts, improving explanations, and debugging parts of the workflow. AI was also used to help translate technical results into clearer report text. The analysis itself was still based on the datasets, R scripts, maps, and outputs produced during the project. AI was not used as a replacement for the spatial analysis, but as a support tool during coding and phrasing.</p>
</section>
<section id="future-improvements" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="future-improvements"><span class="header-section-number">6.6</span> Future improvements</h2>
<p>Future research should first try to use actual pluvial flood depth or flood risk maps for both cities. If that dataset is present, it would reduce the dependence on FWEI as a proxy. If comparable water depth maps were available for Delft and Xi’an, the relationship between green space configuration and flooding could be tested more directly.</p>
<p>Like earlier stated, future work could also include more variables. For example drainage infrastructure, soil type, flow accumulation, and sewer capacity could help explain why certain cells show higher detected water values. This would make it easier to separate the role of green space configuration from other flood related factors.</p>
<p>Another useful step would be to test different grid sizes. Comparing 50 m, 100 m, and 200 m grids would show how sensitive the results are to spatial scale. Testing different FWEI thresholds would also help show whether the flood share results are stable or depend strongly on the chosen threshold.</p>
<p>Finally, future researchers should correct the Xi’an grid alignment issue that produced the Type 1 edge artefact. This issue happened because of a communication mismatch during the group workflow. One part of the Xi’an preprocessing was prepared using an older version of the study area grid, which was positioned slightly further south. Later, when the scripts and datasets were combined into one workflow, this mismatch became visible as a narrow Type 1 band along the northern edge of the Xi’an typology map. At that stage, it was already too late to fully backtrack and reprepare all affected datasets in QGIS, because several layers and outputs had already been clipped, processed, and linked to the existing workflow. Therefore, the artefact was kept in the final output, but it was not interpreted as a meaningful spatial typology pattern. Future work should rebuild the Xi’an preprocessing from one single final grid, then rerun the metric calculation and typology construction. This would make the Xi’an typology percentages more accurate and improve the reliability of the final typology map.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-brom2023" class="csl-entry" role="listitem">
Brom, Peta, Kristine Engemann, Christina Breed, Maya Pasgaard, Titilope Onaolapo, and Jens-Christian Svenning. 2023. <span>“A Decision Support Tool for Green Infrastructure Planning in the Face of Rapid Urbanization.”</span> <em>Land</em> 12 (2): 415. <a href="https://doi.org/10.3390/land12020415">https://doi.org/10.3390/land12020415</a>.
</div>
<div id="ref-farhadi2024fwei" class="csl-entry" role="listitem">
Farhadi, Hadi, Hamid Ebadi, Abbas Kiani, and Ali Asgary. 2024. <span>“A Novel Flood/Water Extraction Index (<span>FWEI</span>) for Identifying Water and Flooded Areas Using <span>Sentinel-2</span> Visible and Near-Infrared Spectral Bands.”</span> <em>Stochastic Environmental Research and Risk Assessment</em> 38: 1873–95. <a href="https://doi.org/10.1007/s00477-024-02660-z">https://doi.org/10.1007/s00477-024-02660-z</a>.
</div>
<div id="ref-meerow2019" class="csl-entry" role="listitem">
Meerow, Sara. 2019. <span>“A Green Infrastructure Spatial Planning Model for Evaluating Ecosystem Service Tradeoffs and Synergies Across Three Coastal Megacities.”</span> <em>Environmental Research Letters</em> 14 (12): 125011. <a href="https://doi.org/10.1088/1748-9326/ab502c">https://doi.org/10.1088/1748-9326/ab502c</a>.
</div>
<div id="ref-prokic2019" class="csl-entry" role="listitem">
Prokić, Marija, Stevan Savić, and Dragoslav Pavić. 2019. <span>“Pluvial Flooding in Urban Areas Across the European Continent.”</span> <em>Geographica Pannonica</em> 23 (4): 216–32. <a href="https://doi.org/10.5937/gp23-23508">https://doi.org/10.5937/gp23-23508</a>.
</div>
<div id="ref-sarabi2022" class="csl-entry" role="listitem">
Sarabi, Shahryar, Qi Han, Bauke de Vries, and A. Georges L. Romme. 2022. <span>“The Nature-Based Solutions Planning Support System: A Playground for Site and Solution Prioritization.”</span> <em>Sustainable Cities and Society</em> 78: 103608. <a href="https://doi.org/10.1016/j.scs.2021.103608">https://doi.org/10.1016/j.scs.2021.103608</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../sections/typology.html" class="pagination-link" aria-label="Typology construction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Typology construction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../sections/conclusion.html" class="pagination-link" aria-label="Conclusion">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Conclusion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/edit/main/sections/discussion.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/blob/main/sections/discussion.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/Applied-Spatial-Analytics/create-your-report-groupc.git/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>